name: JOS.Echo

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      semver2: ${{ steps.nbgv.outputs.SemVer2 }}
      version: ${{ steps.nbgv.outputs.Version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dotnet/nbgv@master
        id: nbgv
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          dotnet-quality: 'preview'
      - name: Build
        run: |
          dotnet build src/JOS.Echo  -c Release /p:AssemblyVersion=${{ steps.nbgv.outputs.version }} /p:InformationalVersion=${{steps.nbgv.outputs.semver2}} --verbosity minimal
      # Docker
      - name: Docker - Setup QEMU
        uses: docker/setup-qemu-action@v2   # https://github.com/docker/setup-qemu-action
      - name: Docker - Setup Buildx
        id: build
        uses: docker/setup-buildx-action@v2 # https://github.com/docker/setup-buildx-action
      - name: Docker - Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker - Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./src/JOS.Echo/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/jos-echo:latest
            ghcr.io/${{ github.repository_owner }}/jos-echo:${{ steps.nbgv.outputs.semver2 }}
