name: JOS.Echo

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      semver2: ${{ steps.nbgv.outputs.SemVer2 }}
      version: ${{ steps.nbgv.outputs.Version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dotnet/nbgv@master
        id: nbgv
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: dotnet build
        run: |
          dotnet test -c Release /p:AssemblyVersion=${{ steps.nbgv.outputs.version }} /p:InformationalVersion=${{steps.nbgv.outputs.semver2}} --verbosity minimal
      - name: Docker - Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker - Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./src/JOS.Echo/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/jos-echo:latest
            ghcr.io/${{ github.repository_owner }}/jos-echo:${{ steps.nbgv.outputs.semver2 }}
      - uses: actions/checkout@v4
        name: GitOps - Checkout
        with:
          repository: joseftw/jos.yoda.infra
          ref: 'develop'
          token: ${{ secrets.JOS_YODA_PAT }}
          fetch-depth: 0
          path: jos.yoda.infra
      - name: GitOps - Patch and push
        run: |
          git -C jos.yoda.infra config user.name "jos-yoda"
          git -C jos.yoda.infra config user.email "144553819+jos-yoda@users.noreply.github.com"
          sed -i'.bak' -e 's|/jos-echo:*.*.*-*.*$|/jos-echo:${{steps.nbgv.outputs.semver2}}|g' jos.yoda.infra/apps/internal/jos.echo/deployment.yml
          git -C jos.yoda.infra commit -am "jos-echo ${{steps.nbgv.outputs.semver2}}"
          git -C jos.yoda.infra push origin develop
